version = 1

exclude_patterns = [
  "resources/**",
  "dist/**"
]

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "jquery",
    "nodejs",
    "browser"
  ]