export const MEGAPHONE_STATE_NAME = 'yacaMegaphone'
export const PHONE_SPEAKER_STATE_NAME = 'yacaPhoneSpeaker'
export const LIP_SYNC_STATE_NAME = 'yacaLipSync'
export const VOICE_RANGE_STATE_NAME = 'yacaVoiceRange'
export const GLOBAL_ERROR_LEVEL_STATE_NAME = 'yacaGlobalErrorLevel'
